<?php  //[STAMP] 10b523949c1ce5daf485fa87ab69c690
namespace Vjik\Codeception\DatabasePopulator\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
