<?php  //[STAMP] 8903f78186117b2aaa3414d55225614d
namespace Vjik\Codeception\DatabasePopulator\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
